name: test_cli
on: push
permissions:
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      # Uncomment and fix this block if needed
      # - name: Install MPI dependencies (Ubuntu/Mac)
      #   if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      #   run: |
      #     if [ "${{ runner.os }}" == "Linux" ]; then
      #       sudo apt-get update
      #       sudo apt-get install -y libopenmpi-dev
      #     elif [ "${{ runner.os }}" == "macOS" ]; then
      #       brew install mpich
      #     fi
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt     
      #    pip install .[heavy]  # Install the heavy dependencies
          pip install flake8 pytest
      - name: Lint code with flake8
        run: |
          flake8 glupredkit tests --count --select=E9,F63,F7,F82 --show-source --statistics --max-complexity=10 --max-line-length=127 --exit-zero
      - name: Run Integration Tests
        run: |
          pytest tests/test_cli.py