name: integration_tests
on: push
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libopenmpi-dev
        run: sudo apt-get update && sudo apt-get install -y libopenmpi-dev
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt     
          pip install flake8 pytest
      - name: Lint code with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 glupredkit --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 glupredkit --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          flake8 tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Integration Tests
        run: |
          pytest