name: Test PyPi Release

on:
  workflow_dispatch:  # Allows manual trigger
  pull_request: # Workaround to get the action to show up before merge to main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine bumpversion

      - name: Set up Git user
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

      - name: Bump version
        id: bump_version
        run: |
          bumpversion patch # Adjust this if you want to bump major or minor versions
          git add .  # Add updated files to the commit
          git commit -m "Bump version to $(bumpversion --list | grep current_version | cut -d '=' -f 2 | xargs)"
          git tag $(python setup.py --version)  # Create a new tag with the new version
          git push
          git push --tags  # Push the new tag to the remote repository

      - name: Clean up old builds
        run: |
          rm -rf dist build *.egg-info

      - name: Build and upload package to Test PyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
