name: Test PyPi Release

on:
  workflow_dispatch:  # Allows manual trigger
  pull_request: # Workaround to get the action to show up before merge to main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine bump2version

      - name: Set up Git user
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

      - name: Checkout the PR branch
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:${{ github.head_ref }}
          git checkout ${{ github.head_ref }}

      - name: Bump version
        id: bump_version
        run: |
          # Bump the version in setup.py and pyproject.toml
          bump2version patch --allow-dirty --verbose  # Ensure you see what's happening
      
          # Capture the new version
          NEW_VERSION=$(bump2version --dry-run --list patch | grep new_version | cut -d '=' -f 2 | xargs)
          echo "New version: ${NEW_VERSION}"  # Debug output
      
          # Ensure changes are staged for commit
          git add setup.py pyproject.toml
      
          # Check if there are any changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Bump version to ${NEW_VERSION}"
            git push origin HEAD
            git push --tags  # Push tags if needed
          fi

      - name: Clean up old builds
        run: |
          rm -rf dist build *.egg-info

      - name: Build and upload package to Test PyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}

